trimble-oss/tierceron

buildopts/coreopts/options_common.go
buildopts/coreopts/options_tc.go
buildopts/deployopts/deploy_common.go
buildopts/deployopts/depoloy_tc.go
buildopts/flowopts/flow_common.go
buildopts/flowopts/flow_tc.go
buildopts/options_common.go
buildopts/options_tc.go
buildopts/tcopts/db_common.go
buildopts/tcopts/db_tc.go
buildopts/testopts/options_flowtest_common.go
buildopts/xencryptopts/xencrypt_common.go
buildopts/xencryptopts/xencrypt_tc.go
trcflow/core/askflume/process_askflume.go
trcflow/core/context.go
trcflow/core/dataFlowStatistics.go
trcflow/flows/process_dataflowstatistics.go
trcsh/trcsh.go
trcx/xutil/xmanager.go

Tierceron wasn't building out of the box.  This makes it possible to build tierceron.
I still had to stub out empty VaultConfig.* projects, but it did compile.

Make possible to compile tierceron externally.

---

atrium/vestibulum/trcdb/trcapimgmtbase/trcapimgmtbase.go

Fixing APIM Url replacement check

Fixing APIM Url replacement check

---

atrium/vestibulum/trcdb/trcapimgmtbase/trcapimgmtbase.go
atrium/vestibulum/trcdb/trcplgtoolbase/trcplgtoolbase.go

Adding API Title replacement + graceful exit

Adding API Title replacement 

---

installation/trccloud/README.md
installation/trccloud/terraform/azure/cloudboot/.gitignore
installation/trclocal/.gitignore
installation/trclocal/README.md
installation/trclocal/trc_templates/Common/sqlcert.pem.mf.tmpl
installation/trclocal/trc_templates/Common/vaultcert.pem.mf.tmpl
installation/trclocal/trc_templates/Common/vaultkey.pem.mf.tmpl
installation/trclocal/trc_templates/Vault/Tierceron/resources/vault_properties.hcl.tmpl
installation/trclocal/trc_templates/Vault/Tierceron/scripts/install.sh.tmpl

Adds steps for running vault locally as a service.

Install setup

---

pkg/core/util/repository/azrcr.go

Fixing null check

---

installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/deploycarrier.sh.tmpl

Updating template for staging/prod support

Updating template for staging/prod support

---

installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/refreshcarriertoken.sh.tmpl
installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/undeploycarrier.sh.tmpl

Deployment template changes

---

pkg/core/util/util.go

Fixing unsafe status code check

Fixing unsafe status code check

---

atrium/vestibulum/trcshbase/trcsh.go
installation/trcdb/trc_templates/TrcVault/SpiralDatabase/config.yml.tmpl
installation/trclocal/README.md
installation/trclocal/trchelloworld/.gitignore
installation/trclocal/trchelloworld/README.md
installation/trclocal/trchelloworld/trc_templates/HelloProject/HelloService/config.yml.tmpl
pkg/capauth/creds.go
pkg/cli/trcconfigbase/trcconfig.go
pkg/core/util/dbutil.go
pkg/utils/autoUtil.go
pkg/validator/db.go

Adding support for cert name for db connections

Adding support for cert name for db connections

---

atrium/vestibulum/trcdb/trcplgtoolbase/trcplgtoolbase.go
atrium/vestibulum/trcshbase/trcsh.go
installation/trcagent/trc_templates/Tierceron/TrcDeploy/setup.cmd.tmpl
installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/refreshcarriertoken.sh.tmpl
installation/trcdb/README.md
pkg/capauth/agentconfig.go
pkg/capauth/creds.go
pkg/cli/trcconfigbase/trcconfig.go
pkg/cli/trcsubbase/trcsub.go

This also provides some functionality needed in one of our environments.

Correct logging.

---

atrium/vestibulum/trcdb/trcplgtoolbase/trcplgtoolbase.go
pkg/cli/trcinitbase/init.go
pkg/core/util/util.go

Adding ability for trcplgtool to unzip at deploy path

Adding ability for trcplgtool to unzip at deploy path

---

atrium/vestibulum/trcflow/deploy/process.go

Adding back write out for override

Adding back write out for override

---

atrium/trcflow/core/context.go

Modifiying db name retrieval

---

atrium/Makefile
atrium/buildopts/localopts/options_common.go
atrium/buildopts/localopts/options_local.go
atrium/go.mod
atrium/go.sum
atrium/vestibulum/carriertest/maindeploytest.go
atrium/vestibulum/plugins/carrier/main.go
atrium/vestibulum/plugins/trcdb/main.go
atrium/vestibulum/trccarrier/carrierfactory/backend.go
atrium/vestibulum/trccarrier/carrierfactory/servercapauth/capauth.go
atrium/vestibulum/trcdb/factory/backend.go
atrium/vestibulum/trcflow/deploy/process.go
installation/trcdb/trc_templates/TrcVault/Certify/config.yml.tmpl

1. Function name cleanup.
2. Package structure cleanup.
3. Adding optional newrelic logging support.
4. Re-adding support for plugin builds that support self signed certificates.

Optional newrelic, self signed certs,

---

pkg/trcinit/initlib/vault-seed.go

Silencing Sensitive Log

---

atrium/go.mod
atrium/go.sum

Fix some broken atrium builds due to newly introduced import dependencies.

Fix import dependency issues.

---

installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/fullcarrieragentdeploy.sh.tmpl

Adding full deployment script

---

installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/fullhivedeploy.sh.tmpl

Adding full hive deployment script

Adding full hive deployment script

---

atrium/vestibulum/plugins/cursor/cursorlib/cursorlib.go
atrium/vestibulum/trccarrier/carrierfactory/backend.go
buildopts/cursoropts/buildopts.go
buildopts/cursoropts/cursorfields.go
buildopts/cursoropts/options_common.go
buildopts/cursoropts/options_trcshcurator.go
buildopts/cursoropts/options_trcshcursoraw.go
buildopts/cursoropts/options_trcshcursork.go
pkg/utils/vaultUtil.go

This gets curator and possibly cursor back up and running with latest changes

Address new map type

---

atrium/vestibulum/trcshbase/trcsh.go

Also fixes duplicate log construction in kernel initialization.

Fix crashing on improper ptr initialization

---

atrium/speculatio/fenestra/data/serverdata.go
atrium/vestibulum/cmd/trcplgtool/trcplgtool.go
atrium/vestibulum/trcdb/trcplgtoolbase/trcplgtoolbase.go
atrium/vestibulum/trcsh/deployutil/deployutil.go
atrium/vestibulum/trcshbase/trcsh.go
pkg/cli/trcconfigbase/trcconfig.go
pkg/cli/trcinitbase/init.go
pkg/cli/trcpubbase/trcpub.go
pkg/cli/trcsubbase/trcsub.go
pkg/cli/trcxbase/trcxbase.go
pkg/core/cache/tokencache.go
pkg/core/core.go
pkg/trcx/xutil/xmanager.go
pkg/utils/autoUtil.go
pkg/utils/vaultUtil.go

1. Fixes certify
2. Adds back in support for token only auth for cmd line utils.

Checkin does several things:

---

atrium/trcdb/db.go

Fixing tiny regression

---

atrium/vestibulum/trcdb/trcplgtoolbase/trcplgtoolbase.go

matching criteria on https://learn.microsoft.com/en-us/azure/container-registry/container-registry-concepts#repository

string validation for pluginName
